//code generated by chatgpt 3.5
import React, { useState, useRef } from 'react';

const VideoComponent = ({ videoURL  }) => {
  const videoRef = useRef(null);


  return (
    <div>
      <iframe
        ref={videoRef}
        width="560"
        height="315"
        src={videoURL}
        frameBorder="0"
        allow="autoplay; encrypted-media"
        allowFullScreen
        title="YouTube Video"
      ></iframe>
      <div>
      </div>
    </div>
  );
};

export default VideoComponent;
