// Code generated by ChatGPT
import React, { Component } from 'react';

class WebcamComponent extends Component {
  constructor(props) {
    super(props);
    this.videoRef = React.createRef();
  }

  componentDidMount() {
    // Access the user's webcam and set it as the source for the video element
    navigator.mediaDevices.getUserMedia({ video: true })
      .then((stream) => {
        this.videoRef.current.srcObject = stream;
      })
      .catch((error) => {
        console.error('Error accessing the webcam:', error);
      });
  }

  render() {
    return (
      <div>
        <video
          ref={this.videoRef}
          autoPlay
          playsInline
          muted // Mute the video to avoid feedback noise
          style={{ width: '100%', maxWidth: '600px' }}
        />
      </div>
    );
  }

  componentWillUnmount() {
    if (this.videoRef.current.srcObject) {
      // Stop the webcam stream when the component unmounts
      const tracks = this.videoRef.current.srcObject.getTracks();
      tracks.forEach((track) => track.stop());
    }
  }
}

export default WebcamComponent;
